Efficiency Change
Team293/Octabot_V2 pull request #15
Opened 2022-12-12 20:57 UTC by TreeBronch

2022-12-13 16:51 UTC, closed without merging

2022-12-13 16:51 UTC, bjmcternan requested changes

2022-12-13 16:51 UTC, bjmcternan commented on src/main/java/frc/robot/classes/Kinematics.java
> +    return false;
Let's only have one return statement. 
`boolean retVal = false;`

`blah`
`return retval;`

2022-12-13 16:51 UTC, bjmcternan commented on src/main/java/frc/robot/classes/Kinematics.java
> +    retval = retval % Math.PI
Missing a `;`

2022-12-13 16:51 UTC, bjmcternan commented on src/main/java/frc/robot/classes/Kinematics.java
> +    retval = retval % Math.PI
This is not equivalent to the previous code and will result in an error if the value given is between 1 PI and 2PI.
If you want to simplify this you will need to do `retval = retval % (2*Math.PI);`

2022-12-14 02:08 UTC, maxim-kudryashov commented on src/main/java/frc/robot/classes/Kinematics.java
> +    retval = retval % Math.PI
Oh mb. I forgot to add the *2 part. Gj noticing that tho.